### ISSUE TITLE
how to get the store cart data in app dashbords.

### ISSUE THREAD

**Issue by ersanjay5991** [bigcommerce/sample-app-nodejs#157]
I am Referring to the cart API from the official document.
[https://developer.bigcommerce.com/api-reference/eb3777c8094b0-get-a-cart](https://developer.bigcommerce.com/api-reference/eb3777c8094b0-get-a-cart)

I was not able to find the  cartId so Where to get the cartId.

```
 const { data } = await bigcommerce.get('/carts/');
        console.log(data);
res.status(200).json(data);
```

Error.

Request returned error code: 404 and body: {"status":404,"type":"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes"}

**Comment by bc-chaz** [comment]
Hi @ersanjay5991 the GitHub Issues section of this repo is for bugs and issues related to the Sample Application. The questions you have are related to our general APIs. For support, please check out our [support page](https://developer.bigcommerce.com/docs/ZG9jOjM4MzMyNTU-support), which includes links to our Developer Community, Blog, and Partner Support Team. As this isn't an issue with the Sample Application, I will close this ticket.

In regards to your specific question, if you scroll down on the API documentation link you provided, it states under `Body` that "Cart ID, provided after creating a cart with a POST request." This means you first need to create a cart in order to have a cart id.

**Comment by ersanjay5991** [comment]
@bc-chaz   thanks I take care.  but I create a support ticket and still not get any update 
Case #: 05880309
