### ISSUE TITLE
cart data

### ISSUE THREAD

**Issue by Mpese-Joao** [bigcommerce/sample-app-nodejs#159]
I want to kno if it is possible to access the cart data through the App?
I'm asking because i'm developing an app to read cart data. But whenever a press the button i get 401 error:

const fetchBigCommerceData = async () => {
try {
const response = await fetch(
"[https://api.bigcommerce.com/stores/aherf0o3nw/v3/carts/{CartId}](https://api.bigcommerce.com/stores/aherf0o3nw/v3/carts/%7BCartId%7D)",
{
headers: {
"Accept" : "application/json",
"Content-Type" : "application/json",
"X-Auth-Token" : "4*****************************,
"X-Auth-Client" : "a*****************************",
},
mode: "no-cors",
}
);

**Comment by bc-nekisham** [comment]
Hi @Mpese-Joao  the GitHub Issues section of this repo is for bugs and issues related to the Sample Application. The questions you have are related to our general APIs. For support, please check out our [support page](https://developer.bigcommerce.com/docs/ZG9jOjM4MzMyNTU-support), which includes links to our Developer Community, Blog, and Partner Support Team. As this isn't an issue with the Sample Application, I will close this ticket.


In regards, to your specific question, the reason you are getting a `401` error is because you're treating a string template literal as a regular string (i.e. you're not passing in the actual CartId to {CartId})
