### ISSUE TITLE
Getting errors whit template app 

### ISSUE THREAD

**Issue by JosukeH** [bigcommerce/sample-app-nodejs#96]
Im getting error on this app on the load of the products, on my Ngrok i'm getting error GET 500 on the end point 

`GET /API/products/list` 500 interntal Server Error

otherwise, I didn't have a DB integrated whit my sample-app-nodejs/next

**Comment by JosukeH** [comment]
![image](https://user-images.githubusercontent.com/41598663/165861678-a0457058-218e-46d2-95fc-14cef0646a41.png)

**Comment by JosukeH** [comment]
![image](https://user-images.githubusercontent.com/41598663/165861718-48de34cb-8988-42c8-a1d7-5b27d1c555f4.png)
![image](https://user-images.githubusercontent.com/41598663/165861752-cd34266f-4c92-4966-aba3-3200e7c98a2e.png)

**Comment by bc-chaz** [comment]
Hi @JosukeH, in order to make any calls to our APIs from within the sample application, a database is required. This enables the application to securely store the OAuth token which is then required to fetch any of our APIs. Please try connecting a db - the sample application provides for both cloud-based (Google Firebase) as well as a traditional SQL db. For additional information, please check out our step-by-step tutorial - https://developer.bigcommerce.com/docs/ZG9jOjE4MjIyODMz-step-3-integrate-the-big-commerce-api-and-add-a-database

**Comment by bc-chaz** [comment]
> > 
> 
> Thanks @bc-chaz , do you have any guide for use MongoDB instead of those?

@JosukeH at this time the closest we have is Firebase
