### ISSUE TITLE
Tutorial Error  - Unexpected token '.' in ButtonGroup.js

### ISSUE THREAD

**Issue by mourogers** [bigcommerce/sample-app-nodejs#98]
Following the first step of the tutorial ([Step 1: Set up Your Local Environment](https://developer.bigcommerce.com/docs/ZG9jOjE4MjIyODMx-step-1-set-up-your-local-environment)) returns an error when running the local dev server.

M1 macOS 12.3

```
Server Error
SyntaxError: Unexpected token '.'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/Path/to/App/node_modules/ (bigcommerce/big-design/dist/cjs/components/ButtonGroup/ButtonGroup.js (55)
wrapSafe
internal/modules/cjs/loader.js (915:16)
Module._compile
internal/modules/cjs/loader.js (963:27)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1027:10)
Module.load
internal/modules/cjs/loader.js (863:32)
Function.Module._load
internal/modules/cjs/loader.js (708:14)
Module.require
internal/modules/cjs/loader.js (887:19)
require
internal/modules/cjs/helpers.js (74:18)
Object.<anonymous>
file:////Path/to/App/node_modules/@bigcommerce/big-design/dist/cjs/components/ButtonGroup/index.js (7:20)
Module._compile
internal/modules/cjs/loader.js (999:30)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1027:10)
```

**Comment by bc-chaz** [comment]
@mourogers this issue appears to be coming from one of the npm packages, which is beyond the control of this repo. More likely than not, the issue is coming from attempting to install a newer version of a package which has breaking changes - please see the [note here](https://developer.bigcommerce.com/docs/ZG9jOjE4MjIyODMx-step-1-set-up-your-local-environment#install-npm-packages) about checking out the exact npm package versions used in the sample app. You can also directly navigate to https://github.com/bigcommerce/sample-app-nodejs/blob/step-1-app-foundation/package.json.

To install a specific version of a package, please follow `npm install <pkg>@<version>` found [here](https://docs.npmjs.com/cli/v8/commands/npm-install).
